package br.com.cams7.sisbarc.aal.service.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 * 
 */
@WebServiceClient(name = AppArduinoServiceImplService.SEVICE_NAME + "Service", targetNamespace = AppArduinoService.SEVICE_NAMESPACE, wsdlLocation = AppArduinoServiceImplService.WSDL_LOCATION)
public class AppArduinoServiceImplService extends Service {

	public static final String WSDL_LOCATION = "http://localhost:8080/acende_apaga_leds/aal_monitor?wsdl";
	public static final String SEVICE_NAME = AppArduinoService.SEVICE_NAME
			+ "Impl";

	private final static URL APPARDUINOSERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static WebServiceException APPARDUINOSERVICEIMPLSERVICE_EXCEPTION;
	private final static QName APPARDUINOSERVICEIMPLSERVICE_QNAME = new QName(
			AppArduinoService.SEVICE_NAMESPACE, SEVICE_NAME + "Service");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(WSDL_LOCATION);
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		APPARDUINOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
		APPARDUINOSERVICEIMPLSERVICE_EXCEPTION = e;
	}

	public AppArduinoServiceImplService() {
		super(__getWsdlLocation(), APPARDUINOSERVICEIMPLSERVICE_QNAME);
	}

	public AppArduinoServiceImplService(WebServiceFeature... features) {
		super(__getWsdlLocation(), APPARDUINOSERVICEIMPLSERVICE_QNAME, features);
	}

	public AppArduinoServiceImplService(URL wsdlLocation) {
		super(wsdlLocation, APPARDUINOSERVICEIMPLSERVICE_QNAME);
	}

	public AppArduinoServiceImplService(URL wsdlLocation,
			WebServiceFeature... features) {
		super(wsdlLocation, APPARDUINOSERVICEIMPLSERVICE_QNAME, features);
	}

	public AppArduinoServiceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public AppArduinoServiceImplService(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns AppArduinoService
	 */
	@WebEndpoint(name = SEVICE_NAME + "Port")
	public AppArduinoService getAppArduinoServiceImplPort() {
		return super.getPort(new QName(AppArduinoService.SEVICE_NAMESPACE,
				SEVICE_NAME + "Port"), AppArduinoService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns AppArduinoService
	 */
	@WebEndpoint(name = SEVICE_NAME + "Port")
	public AppArduinoService getAppArduinoServiceImplPort(
			WebServiceFeature... features) {
		return super.getPort(new QName(AppArduinoService.SEVICE_NAMESPACE,
				SEVICE_NAME + "Port"), AppArduinoService.class, features);
	}

	private static URL __getWsdlLocation() {
		if (APPARDUINOSERVICEIMPLSERVICE_EXCEPTION != null) {
			throw APPARDUINOSERVICEIMPLSERVICE_EXCEPTION;
		}
		return APPARDUINOSERVICEIMPLSERVICE_WSDL_LOCATION;
	}

}
