package br.com.cams7.sisbarc.aal.service.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

import br.com.cams7.sisbarc.aal.jpa.domain.Pin.Evento;
import br.com.cams7.sisbarc.aal.jpa.domain.Pin.Intervalo;
import br.com.cams7.sisbarc.aal.jpa.domain.entity.LEDEntity.EstadoLED;
import br.com.cams7.sisbarc.aal.jpa.domain.pk.PinPK;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 * 
 */
@WebService(name = AppArduinoService.SEVICE_NAME, targetNamespace = AppArduinoService.SEVICE_NAMESPACE)
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({ ObjectFactory.class })
public interface AppArduinoService {

	public static final String SEVICE_NAME = "AppArduinoService";
	public static final String SEVICE_NAMESPACE = "http://ws.aal.sisbarc.cams7.com.br/";

	public static final String WEB_SEVICE = SEVICE_NAMESPACE + SEVICE_NAME;
	public static final String WEB_RESULT = "return";

	/**
	 * 
	 * @param arg0
	 * @return returns br.com.cams7.sisbarc.aal.ws.LedEntityArray
	 */
	@WebMethod
	@WebResult(partName = WEB_RESULT)
	@Action(input = WEB_SEVICE + "/buscaEstadoLEDsRequest", output = WEB_SEVICE
			+ "/buscaEstadoLEDsResponse")
	public LEDEntityArray buscaEstadoLEDs(
			@WebParam(name = "arg0", partName = "arg0") PinPKArray arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns br.com.cams7.sisbarc.aal.ws.EstadoLED
	 */
	@WebMethod
	@WebResult(partName = WEB_RESULT)
	@Action(input = WEB_SEVICE + "/alteraEstadoLEDRequest", output = WEB_SEVICE
			+ "/alteraEstadoLEDResponse")
	public EstadoLED alteraEstadoLED(
			@WebParam(name = "arg0", partName = "arg0") PinPK arg0,
			@WebParam(name = "arg1", partName = "arg1") EstadoLED arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns br.com.cams7.sisbarc.aal.ws.PinArray
	 */
	@WebMethod
	@WebResult(partName = WEB_RESULT)
	@Action(input = WEB_SEVICE + "/buscaDadosRequest", output = WEB_SEVICE
			+ "/buscaDadosResponse")
	public PinArray buscaDados(
			@WebParam(name = "arg0", partName = "arg0") PinPKArray arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns br.com.cams7.sisbarc.aal.ws.Evento
	 */
	@WebMethod
	@WebResult(partName = WEB_RESULT)
	@Action(input = WEB_SEVICE + "/alteraEventoRequest", output = WEB_SEVICE
			+ "/alteraEventoResponse")
	public Evento alteraEvento(
			@WebParam(name = "arg0", partName = "arg0") PinPK arg0,
			@WebParam(name = "arg1", partName = "arg1") Evento arg1,
			@WebParam(name = "arg2", partName = "arg2") Intervalo arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns br.com.cams7.sisbarc.aal.ws.PinArray
	 */
	@WebMethod
	@WebResult(partName = WEB_RESULT)
	@Action(input = WEB_SEVICE + "/alteraEventosRequest", output = WEB_SEVICE
			+ "/alteraEventosResponse")
	public PinArray alteraEventos(
			@WebParam(name = "arg0", partName = "arg0") PinArray arg0);

	/**
	 * 
	 * @throws ArduinoException_Exception
	 */
	@WebMethod
	@Action(input = WEB_SEVICE + "/initRequest", output = WEB_SEVICE
			+ "/initResponse", fault = { @FaultAction(className = ArduinoException_Exception.class, value = WEB_SEVICE
			+ "/init/Fault/ArduinoException") })
	public void init() throws ArduinoException_Exception;

	/**
	 * 
	 * @throws ArduinoException_Exception
	 */
	@WebMethod
	@Action(input = WEB_SEVICE + "/closeRequest", output = WEB_SEVICE
			+ "/closeResponse", fault = { @FaultAction(className = ArduinoException_Exception.class, value = WEB_SEVICE
			+ "/close/Fault/ArduinoException") })
	public void close() throws ArduinoException_Exception;

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = WEB_RESULT)
	@Action(input = WEB_SEVICE + "/getSerialPortRequest", output = WEB_SEVICE
			+ "/getSerialPortResponse")
	public String getSerialPort();

	/**
	 * 
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(partName = WEB_RESULT)
	@Action(input = WEB_SEVICE + "/isInitializedRequest", output = WEB_SEVICE
			+ "/isInitializedResponse")
	public boolean isInitialized();

	/**
	 * 
	 * @return returns int
	 */
	@WebMethod
	@WebResult(partName = WEB_RESULT)
	@Action(input = WEB_SEVICE + "/getSerialBaudRateRequest", output = WEB_SEVICE
			+ "/getSerialBaudRateResponse")
	public int getSerialBaudRate();

	/**
	 * 
	 * @return returns long
	 */
	@WebMethod
	@WebResult(partName = WEB_RESULT)
	@Action(input = WEB_SEVICE + "/getSerialThreadTimeRequest", output = WEB_SEVICE
			+ "/getSerialThreadTimeResponse")
	public long getSerialThreadTime();

}
