package br.com.cams7.sisbarc.aal.service.ws;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 * 
 */
@WebFault(name = ArduinoException.EXCEPTION_NAME, targetNamespace = AppArduinoService.SEVICE_NAMESPACE)
public class ArduinoException_Exception extends Exception {

	private static final long serialVersionUID = 1L;

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private ArduinoException faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public ArduinoException_Exception(String message, ArduinoException faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public ArduinoException_Exception(String message,
			ArduinoException faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: br.com.cams7.sisbarc.aal.ws.ArduinoException
	 */
	public ArduinoException getFaultInfo() {
		return faultInfo;
	}

}
